name: Update Android Studio Spec File

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
  schedule:
    # Runs at 4:00 AM UTC every day
    - cron: '0 4 * * *'

jobs:
  update-spec-file:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required for pushing changes to the repository
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }} # Use GITHUB_TOKEN for authentication

      - name: Set up environment
        run: |
          sudo apt-get update
          sudo apt-get install -y curl jq # jq for potential future JSON use

      - name: Update spec file and commit changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          SPEC_FILE="android-studio.spec"
          
          echo "Fetching the latest Android Studio version..."

          # Temporary debug: Save page content for inspection if needed
          curl -s https://developer.android.com/studio/releases > releases.html
          curl -s https://developer.android.com/studio > studio.html

          # Method 1: Scrape from releases page header (most reliable for latest stable)
          LATEST_VERSION=$(curl -s --retry 3 --retry-delay 5 https://developer.android.com/studio/releases \
            | grep -oP 'Android Studio \K(\d{4}\.\d+\.\d+)' \
            | head -1)

          # Method 2: Fallback to main studio page header
          if [ -z "$LATEST_VERSION" ]; then
            echo "Method 1 failed. Trying main page header..."
            LATEST_VERSION=$(curl -s --retry 3 --retry-delay 5 https://developer.android.com/studio \
              | grep -oP 'Android Studio \K(\d{4}\.\d+\.\d+)' \
              | head -1)
          fi

          # Method 3: Fallback to download filename pattern on main page (includes patch if available)
          if [ -z "$LATEST_VERSION" ]; then
            echo "Method 2 failed. Trying download filename..."
            LATEST_VERSION=$(curl -s --retry 3 --retry-delay 5 https://developer.android.com/studio \
              | grep -oP 'android-studio-\K\d{4}\.\d+\.\d+(?:\.\d+)?' \
              | sort -V | head -1 \
              | cut -d. -f1-3)  # Trim to major.minor.patch if extra patch present
          fi

          # Method 4: Broad fallback from releases page table or any mention
          if [ -z "$LATEST_VERSION" ]; then
            echo "Method 3 failed. Trying broad search on releases page..."
            LATEST_VERSION=$(curl -s --retry 3 --retry-delay 5 https://developer.android.com/studio/releases \
              | grep -oP '\d{4}\.\d+\.\d+' \
              | sort -V | tail -n1)
          fi

          # Clean up temp files
          rm -f releases.html studio.html

          if [ -z "$LATEST_VERSION" ]; then
            echo "ERROR: Failed to fetch the latest version from all sources."
            echo "Debug: Last 200 chars of releases page:"
            curl -s https://developer.android.com/studio/releases | tail -c 200
            exit 1
          fi

          echo "Latest available version: $LATEST_VERSION"

          # Validate version format (e.g., YYYY.M.N)
          if ! echo "$LATEST_VERSION" | grep -qE '^[0-9]{4}\.[0-9]+\.[0-9]+$'; then
            echo "ERROR: Invalid version format: $LATEST_VERSION"
            exit 1
          fi

          # Check if spec file exists
          if [ ! -f "$SPEC_FILE" ]; then
            echo "ERROR: Spec file not found: $SPEC_FILE"
            exit 1
          fi

          # Get current version from spec file (trim whitespace)
          CURRENT_VERSION=$(grep -i "^Version:" "$SPEC_FILE" | awk '{print $2}' | tr -d '[:space:]')
          echo "Current spec file version: $CURRENT_VERSION"

          # Compare versions
          if [ "$LATEST_VERSION" = "$CURRENT_VERSION" ]; then
            echo "Version is already up to date."
            exit 0
          fi

          echo "New version found. Updating spec file..."
          
          # Debug: Show current spec file content
          echo "=== SPEC FILE DEBUG ==="
          echo "Spec file exists: $(test -f "$SPEC_FILE" && echo "YES" || echo "NO")"
          echo "Spec file size: $(wc -c < "$SPEC_FILE" 2>/dev/null || echo "0") bytes"
          echo "First 10 lines of spec file:"
          head -10 "$SPEC_FILE" 2>/dev/null || echo "Cannot read spec file"
          echo "Lines containing 'version' (case insensitive):"
          grep -i "version" "$SPEC_FILE" 2>/dev/null || echo "No version lines found"
          echo "========================"

          # Create backup
          cp "$SPEC_FILE" "${SPEC_FILE}.backup" || {
            echo "ERROR: Failed to create backup of spec file"
            exit 1
          }

          # Check if Version line exists, if not create the spec file structure
          if ! grep -q -i "^Version:" "$SPEC_FILE"; then
            echo "No Version: line found in spec file. Current content:"
            cat "$SPEC_FILE" || echo "Cannot display file content"
            
            # If the file is empty or doesn't have version line, we need to handle this
            if [ ! -s "$SPEC_FILE" ]; then
              echo "ERROR: Spec file is empty. Cannot proceed without a proper spec file template."
              exit 1
            else
              echo "Adding Version line to existing spec file..."
              # Try to add version line in appropriate location (after Name: if it exists)
              if grep -q "^Name:" "$SPEC_FILE"; then
                sed -i '/^Name:/a\Version: '"$LATEST_VERSION" "$SPEC_FILE"
              else
                # Add at the beginning
                sed -i '1i\Version: '"$LATEST_VERSION" "$SPEC_FILE"
              fi
            fi
          else
            echo "Before update - Version line:"
            grep -i "^Version:" "$SPEC_FILE" | cat -A
            
            # Update the spec file with the new version
            sed -i "s/^Version:.*/Version: $LATEST_VERSION/" "$SPEC_FILE"
          fi

          echo "After update - Version line:"
          grep -i "^Version:" "$SPEC_FILE" | cat -A || echo "No Version line found after update"

          # Verify the update with multiple extraction methods
          UPDATED_VERSION=""
          
          # Method 1: Standard extraction
          UPDATED_VERSION=$(grep -i "^Version:" "$SPEC_FILE" | awk '{print $2}' | tr -d '[:space:]' 2>/dev/null)
          
          # Method 2: If method 1 fails, try alternative parsing
          if [ -z "$UPDATED_VERSION" ]; then
            UPDATED_VERSION=$(grep -i "^Version:" "$SPEC_FILE" | sed 's/^[Vv]ersion:[[:space:]]*//' | tr -d '[:space:]' 2>/dev/null)
          fi
          
          # Method 3: If both fail, try cut
          if [ -z "$UPDATED_VERSION" ]; then
            UPDATED_VERSION=$(grep -i "^Version:" "$SPEC_FILE" | cut -d':' -f2 | tr -d '[:space:]' 2>/dev/null)
          fi

          echo "Extracted updated version: '$UPDATED_VERSION'"
          echo "Expected version: '$LATEST_VERSION'"

          if [ -z "$UPDATED_VERSION" ]; then
            echo "ERROR: Could not extract version from spec file after update."
            echo "Full spec file content after update:"
            cat "$SPEC_FILE"
            # Restore backup
            mv "${SPEC_FILE}.backup" "$SPEC_FILE"
            exit 1
          fi

          if [ "$UPDATED_VERSION" != "$LATEST_VERSION" ]; then
            echo "ERROR: Failed to update spec file correctly."
            echo "Full version line after update:"
            grep -i "^Version:" "$SPEC_FILE" || echo "Version line not found"
            echo "Full spec file content:"
            cat "$SPEC_FILE"
            # Restore backup
            mv "${SPEC_FILE}.backup" "$SPEC_FILE"
            exit 1
          fi

          # Remove backup on success
          rm -f "${SPEC_FILE}.backup"

          # Configure git
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'github-actions@github.com'

          # Commit and push changes
          if ! git diff --quiet "$SPEC_FILE"; then
            echo "Committing and pushing changes..."
            git add "$SPEC_FILE"
            git commit -m "chore(version): Bump Android Studio to $LATEST_VERSION"
            git push
          else
            echo "WARNING: No changes detected in spec file despite version difference."
            echo "Git diff output:"
            git diff "$SPEC_FILE"
            exit 1
          fi
