name: Check for Android Studio Updates

on:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * *'
  push: # Runs the workflow on every push to the main branch
    branches:
      - main

permissions:
  contents: write

jobs:
  check-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get Current Version from Spec
        id: spec
        run: |
          CURRENT_VERSION=$(grep -i '^Version:' android-studio.spec | awk '{print $2}')
          echo "Current spec version: $CURRENT_VERSION"
          echo "version=$CURRENT_VERSION" >> $GITHUB_OUTPUT

      - name: Fetch Latest Version from Google
        id: remote
        run: |
          # This is the most reliable method. It finds the version string directly
          # from the download filename, which is less likely to change than other text.
          LATEST_VERSION=$(curl -sL https://developer.android.com/studio | \
                           grep -o 'android-studio-[^-]*-linux.tar.gz' | \
                           sed -e 's/android-studio-//' -e 's/-linux.tar.gz//' | \
                           head -n 1)
          
          if [ -z "$LATEST_VERSION" ]; then
            echo "Failed to fetch latest version."
            exit 1
          fi
          
          echo "Latest remote version: $LATEST_VERSION"
          echo "version=$LATEST_VERSION" >> $GITHUB_OUTPUT

      - name: Compare Versions
        id: compare
        run: |
          # This uses 'sort -V' for a safe, reliable version comparison.
          # This prevents the action from downgrading a manual update.
          SPEC_VER="${{ steps.spec.outputs.version }}"
          REMOTE_VER="${{ steps.remote.outputs.version }}"
          
          echo "Spec version: $SPEC_VER"
          echo "Remote version: $REMOTE_VER"
          
          # Check if the remote version is newer than the spec version
          if [ "$(printf '%s\n' "$SPEC_VER" "$REMOTE_VER" | sort -V | tail -n 1)" == "$REMOTE_VER" ] && [ "$SPEC_VER" != "$REMOTE_VER" ]; then
            echo "Newer remote version found! Proceeding with update."
            echo "update=true" >> $GITHUB_OUTPUT
          else
            echo "Spec version is the same or newer. No update needed."
            echo "update=false" >> $GITHUB_OUTPUT
          fi

      - name: Update Spec File and Push
        if: steps.compare.outputs.update == 'true'
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          
          OLD_VER="${{ steps.spec.outputs.version }}"
          NEW_VER="${{ steps.remote.outputs.version }}"
          
          echo "Updating spec file from $OLD_VER to $NEW_VER..."
          
          # Safely update the Version field
          sed -i "s/^Version:.*$OLD_VER/Version:        $NEW_VER/" android-studio.spec
          
          # Reset Release to 0 or 1 for the new version
          sed -i "s/^Release:.*$/Release:        0/" android-studio.spec
          
          git add android-studio.spec
          git commit -m "Automated version bump to $NEW_VER"
          git push
          echo "Pushed updated spec file to repository."
