name: Check for Android Studio Updates

on:
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab
  schedule:
    - cron: '0 8 * * *' # Runs daily at 08:00 UTC

jobs:
  check-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get Current Version from Spec
        id: spec
        run: |
          # Get the current version from your spec file
          CURRENT_VERSION=$(grep -i '^Version:' android-studio.spec | awk '{print $2}')
          echo "Current spec version: $CURRENT_VERSION"
          echo "version=$CURRENT_VERSION" >> $GITHUB_OUTPUT

      - name: Fetch Latest Version from Google
        id: remote
        run: |
          # Scrape the main download page (not the release notes)
          # Find the exact linux.tar.gz file and extract the version from its name
          LATEST_VERSION=$(curl -sL https://developer.android.com/studio | \
                           grep -o 'android-studio-[0-9.]*-linux.tar.gz' | \
                           sed -e 's/android-studio-//' -e 's/-linux.tar.gz//' | \
                           head -n 1)
          
          if [ -z "$LATEST_VERSION" ]; then
            echo "Failed to fetch latest version."
            exit 1
          fi
          
          echo "Latest remote version: $LATEST_VERSION"
          echo "version=$LATEST_VERSION" >> $GITHUB_OUTPUT

      - name: Compare Versions
        id: compare
        run: |
          echo "Comparing versions..."
          if [ "${{ steps.spec.outputs.version }}" == "${{ steps.remote.outputs.version }}" ]; then
            echo "Versions are the same. No update needed."
            echo "update=false" >> $GITHUB_OUTPUT
          else
            echo "New version found! Proceeding with update."
            echo "update=true" >> $GITHUB_OUTPUT
          fi

      - name: Update Spec File and Push
        if: steps.compare.outputs.update == 'true'
        run: |
          # Set up Git for the bot
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          
          OLD_VER="${{ steps.spec.outputs.version }}"
          NEW_VER="${{ steps.remote.outputs.version }}"
          
          echo "Updating spec file from $OLD_VER to $NEW_VER..."
          
          # Use sed to replace the Version tag
          sed -i "s/^Version:.*$OLD_VER/Version:        $NEW_VER/" android-studio.spec
          
          # Use sed to reset the Release tag to 1 for the new version
          sed -i "s/^Release:.*$/Release:        1/" android-studio.spec
          
          # Commit and push the changes
          git add android-studio.spec
          git commit -m "Automated version bump to $NEW_VER"
          git push
          echo "Pushed updated spec file to repository."
